[package]
name = "AdventOfCode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
grid = "0.15.0"
indicatif = "0.17.9"
itertools = "0.13.0"
ndarray = "0.15.6"
ndarray-linalg = {version="0.16.0", features=["openblas-static"]}
regex = "1.11.1"
